---
# role: ansible-role-ssh
# file: molecule/kvm/molecule.yml

dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/shared/yamllint.yml
platforms:
  - name: ssh-amazon
    image: "jam82/amazon-molecule:latest"
    command: "/usr/lib/systemd/systemd"
    pre_build_image: true
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ssh-arch
    image: "jam82/arch-molecule:latest"
    command: "/usr/lib/systemd/systemd"
    pre_build_image: true
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ssh-centos6
    image: "jam82/centos-molecule:6"
    command: "/sbin/init"
    pre_build_image: true
    privileged: true
  - name: ssh-centos7
    image: "jam82/centos-molecule:7"
    command: "/usr/lib/systemd/systemd"
    pre_build_image: true
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ssh-debian8
    image: "jam82/debian-molecule:8"
    command: "/lib/systemd/systemd"
    pre_build_image: true
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ssh-debian9
    image: "jam82/debian-molecule:9"
    command: "/lib/systemd/systemd"
    pre_build_image: true
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ssh-debian10
    image: "jam82/debian-molecule:10"
    command: "/lib/systemd/systemd"
    pre_build_image: true
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ssh-debian
    image: "jam82/debian-molecule:latest"
    command: "/lib/systemd/systemd"
    pre_build_image: true
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ssh-suse15
    image: "jam82/suse-molecule:15"
    command: "/usr/lib/systemd/systemd"
    pre_build_image: true
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ssh-suse
    image: "jam82/suse-molecule:latest"
    command: "/usr/lib/systemd/systemd"
    pre_build_image: true
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ssh-suse-tumbleweed
    image: "jam82/suse-molecule:tumbleweed"
    command: "/usr/lib/systemd/systemd"
    pre_build_image: true
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ssh-oracle6
    image: "jam82/oracle-molecule:6"
    command: "/sbin/init"
    pre_build_image: true
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ssh-oracle7
    image: "jam82/oracle-molecule:7"
    command: "/usr/lib/systemd/systemd"
    pre_build_image: true
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ssh-oracle
    image: "jam82/oracle-molecule:latest"
    command: "/usr/lib/systemd/systemd"
    pre_build_image: true
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ssh-ubuntu1604
    image: "jam82/ubuntu-molecule:16.04"
    command: "/lib/systemd/systemd"
    pre_build_image: true
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ssh-ubuntu1804
    image: "jam82/ubuntu-molecule:18.04"
    command: "/lib/systemd/systemd"
    pre_build_image: true
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ssh-ubuntu
    image: "jam82/ubuntu-molecule:latest"
    command: "/lib/systemd/systemd"
    pre_build_image: true
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
  playbooks:
    converge: ../shared/playbook.yml
  inventory:
    group_vars:
      all:
        ssh_enabled: True
        ssh_deploy_key: ''
        sshd_listen_addr_v4: ['0.0.0.0']
        sshd_permit_root_login: 'yes'
        ssh_test_create_key: True
        ssh_strict_host_key_checking: 'no'
        ssh_enable_ssh_keysign: 'yes'
        sshd_hostbased_auth: 'yes'
        sshd_shosts_equiv:
          test.example.com: 'testuser'
        sshd_ssh_known_hosts:
          test.example.com: 'test.example.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAgEA1WuHeYhSq0sw6y9iRId7yWpTlcpbyeCOMWYq1ht86DIs2jGRxvkOYxnMQmVsevl2ckuQPAIKgm03bPS1PHYHtRDe72gI90PFtW96fZLn9dsh3HYB6+Bx//aVJ7r3LdLMJr8tcGO378x/hjy01AxbAJJGDGcPecngbffCeDHVdXPpvm88GgPyMtUPaLbFOA5Eq0UyVxQrFj/1iA0Ufy6hDzoyMrg7kK6Bwt2Oa9BoIEM7Y3UqkvANBxlVuO2ChijPgma6aYiL0zN12WBDuwkP5Add/8Q2bTGsMtTGCXAB1UzULwMiFM2JLXwZ74lapd2ZHc/K+oPCT+qq6hND8uUfTMJgSyCVAqavT2x1qaWiVJ3SU2hT7SxjnKekaj/GjBPTbyEWyWDApHQSv4B8ArbLz8AB4FKRvXdG+G5wh1vr0N/cpknIB4VtJWOj4IMfoILNfHfFv/eBUTINpSuZNd0/E7YwR4P+dDMUQB0QPbK7iVBKVCTffgd3GgANUA6rg/FloxOMmitXutCmQPZu4XaL3dq4C7potEH5XPIHvnKeRJtitxOgb1M9B4ulrVspO+sgJRq6ZzJzBECIIhcIJ59RktpPZ1pa4A8wtgoLE0qWxOdkpKTckVHJhYU18UQ1rKaOEKd4upEZSjwGTf4xEDwyKqrc+YBg6ZOTELLRPsdZxSc='
        ssh_host_config:
          '*.example.com':
            HostbasedAuthentication: 'yes'
            GSSAPIAuthentication: 'yes'
scenario:
  name: all
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore"
  directory: ../tests
  options:
    v: true
    sudo: true
  lint:
    name: flake8
