---
# role: ansible-role-ssh
# file: tasks/hostkeys.yml

- name: Check that host key files exist
  stat:
    path: "{{ hostkey.path }}"
  register: hostkey_file

- name: Debug hostkey_file.stat.exists
  debug:
    msg: "hostkey.path: {{ hostkey_file.stat.exists }}"

- name: Create ssh host keys
  shell: "set -o pipefail && echo -e 'y' | ssh-keygen -q -t {{ hostkey.type }} -N '' -f {{ hostkey.path }} >/dev/null"
  args:
    executable: /bin/bash
  changed_when: False
  register: ssh_version
  check_mode: no
  when: (not hostkey_file.stat.exists) | bool
    or (sshd_host_key_regenerate | bool)
