---

- name: Check that host key files exist
  stat:
    path: "{{ hostkey.path }}"
  register: hostkey_file

- name: Create ssh host keys
  shell: "yes y | ssh-keygen -q -t {{ hostkey.type }} -N '' -f {{ hostkey.path }} >/dev/null"
  args:
    executable: /bin/bash
  changed_when: False
  register: ssh_version
  check_mode: no
  when: hostkey_file.stat.exists == False
    or (sshd_host_key_regenerate | bool)