---
# role: ansible-role-ssh
# file: tasks/sshd.yml

- name: debug rekey_limit
  debug:
    msg: "{{ sshd_rekey_limit }}"

- name: Set up sshd configuration in /etc/ssh/sshd_config
  template:
    src: 'etc/ssh/sshd_config.j2'
    dest: '/etc/ssh/sshd_config'
    mode: '0644'
    owner: 'root'
    group: 'root'
    backup: 'yes'
    validate: '/usr/sbin/sshd -T -C user=root -C host=localhost -C addr=localhost -f %s'
  notify: restart sshd

# - name: Create ssh host keys (if non-existend or when forced)
#   shell:
