---
# role: ansible-role-ssh
# file: tasks/version.yml

- name: Determine ssh version
  shell: set -o pipefail && ssh -V 2>&1 | sed -r "s/.*_([0-9.]*).*\s{1}.*/\1/"
  args:
    executable: /bin/bash
  changed_when: False
  register: ssh_version
  check_mode: no

- name: Check for ssh -Q ability (ssh >= 6.3)
  shell: ssh -Q cipher 
  args:
    executable: /bin/bash
  register: check_ssh_q
  changed_when: False
  ignore_errors: True

- name: Determine ssh available ciphers (ssh >= 6.3)
  shell: set -o pipefail && ssh -Q cipher 2>&1
  args:
    executable: /bin/bash
  changed_when: False
  register: ssh_gather_ciphers
  check_mode: no
  when: check_ssh_q is not failed

- name: Set fact ssh_available_ciphers (ssh >= 6.3)
  set_fact:
    ssh_available_ciphers: "{{ ssh_gather_ciphers.stdout.split('\n') }}"
  when: check_ssh_q is not failed

- name: Set fact ssh_available_ciphers (ssh < 6.3)
  set_fact:
    ssh_available_ciphers: ['aes128-ctr','aes192-ctr','aes256-ctr']
  when: check_ssh_q is failed

- name: Determine ssh available kexs
  shell: set -o pipefail && ssh -Q kex 2>&1
  args:
    executable: /bin/bash
  changed_when: false
  register: ssh_gather_kexs
  check_mode: no
  when: check_ssh_q is not failed

- name: Set fact ssh_available_kexs
  set_fact:
    ssh_available_kexs: "{{ ssh_gather_kexs.stdout.split('\n') }}"
  when: check_ssh_q is not failed

- name: Set fact ssh_available_kexs (ssh < 6.3)
  set_fact:
    ssh_available_kexs: ['diffie-hellman-group-exchange-sha256']
  when: check_ssh_q is failed

- name: Determine ssh available keys
  shell: set -o pipefail && ssh -Q key 2>&1
  args:
    executable: /bin/bash
  changed_when: false
  register: ssh_gather_keys
  check_mode: no
  when: check_ssh_q is not failed

- name: Set fact ssh_available_keys
  set_fact:
    ssh_available_keys: "{{ ssh_gather_keys.stdout.split('\n') }}"
  when: check_ssh_q is not failed

- name: Set fact ssh_available_keys (ssh < 6.3)
  set_fact:
    ssh_available_keys: ['ssh-rsa-cert-v01@openssh.com','ssh-rsa']
  when: check_ssh_q is failed

- name: Determine ssh available macs
  shell: set -o pipefail && ssh -Q mac 2>&1
  args:
    executable: /bin/bash
  changed_when: false
  register: ssh_gather_macs
  check_mode: no
  when: check_ssh_q is not failed

- name: Set fact ssh_available_macs
  set_fact:
    ssh_available_macs: "{{ ssh_gather_macs.stdout.split('\n') }}"
  when: check_ssh_q is not failed

- name: Set fact ssh_available_macs (ssh < 6.3)
  set_fact:
    ssh_available_macs: ['hmac-sha2-256','hmac-sha2-512']
  when: check_ssh_q is failed

- name: Set fact ssh_ciphers (ssh_algorithms.ciphers | intersect(ssh_available_ciphers))
  set_fact:
    ssh_ciphers: "{{ ssh_algorithms.ciphers | intersect(ssh_available_ciphers) | join(',') }}"

- name: Set fact ssh_kexs (ssh_algorithms.kexs | intersect(ssh_available_kexs))
  set_fact:
    ssh_kexs: "{{ ssh_algorithms.kexs | intersect(ssh_available_kexs) | join(',') }}"

- name: Set fact ssh_keys (ssh_algorithms.keys | intersect(ssh_available_keys))
  set_fact:
    ssh_keys: "{{ ssh_algorithms.hostkeys | intersect(ssh_available_keys) | join(',') }}"

- name: Set fact ssh_macs (ssh_algorithms.macs | intersect(ssh_available_macs))
  set_fact:
    ssh_macs: "{{ ssh_algorithms.macs | intersect(ssh_available_macs) | join(',') }}"
