---
# role: ansible-role-ssh
# file: molecule/kvm/molecule.yml

dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/shared/yamllint.yml
platforms:
  - name: ssh-default
    image: ${MOLECULE_DIST:-"jam82/ubuntu-molecule:18.04"}
    command: ${MOLECULE_DOCKER_CMD:-""}
    pre_build_image: true
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
  playbooks:
    converge: ../shared/playbook.yml
  inventory:
    group_vars:
      all:
        role_ssh_enabled: true
        sshd_listen_addr_v4: ['0.0.0.0']
        sshd_permit_root_login: 'yes'
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore"
  directory: ../tests
  options:
    v: true
    sudo: true
  lint:
    name: flake8
