---
# role: ansible-role-ssh
# file: molecule/kvm/molecule.yml

dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/shared/yamllint.yml
platforms:
  # - name: ssh-amazon2
  #   image: "jam82/amazon-molecule:2"
  #   pre_build_image: true
  #   privileged: true
  #   volume_mounts:
  #     - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  # - name: ssh-arch
  #   image: "jam82/arch-molecule"
  #   pre_build_image: true
  #   privileged: true
  #   volume_mounts:
  #     - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  # - name: ssh-centos6
  #   image: "jam82/centos-molecule:6"
  #   pre_build_image: true
  #   privileged: true
  #   volume_mounts:
  #     - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  # - name: ssh-centos7
  #   image: "jam82/centos-molecule:7"
  #   pre_build_image: true
  #   privileged: true
  #   volume_mounts:
  #     - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  # - name: ssh-debian8
  #   image: "debian:jessie"
  #   privileged: true
  #   volume_mounts:
  #     - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  # - name: ssh-debian9
  #   image: "debian:stretch"
  #   privileged: true
  #   volume_mounts:
  #     - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  # - name: ssh-opensuse-leap
  #   image: "opensuse:leap"
  #   privileged: true
  #   volume_mounts:
  #     - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  # - name: ssh-oracle7
  #   image: "oraclelinux:7"
  #   privileged: true
  #   volume_mounts:
  #     - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  # - name: ssh-ubuntu1604
  #   image: "jam82/ubuntu1604"
  - name: ssh-ubuntu1804
    image: "1804:latest"
  # - name: ssh-ubuntu1804
  #   image: "ubuntu:18.04"
  #   privileged: true
  #   volume_mounts:
  #     - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
  playbooks:
    converge: ../shared/playbook.yml
  inventory:
    group_vars:
      all:
        role_ssh_enabled: true
        sshd_listen_addr_v4: ['0.0.0.0']
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore"
  directory: ../tests
  options:
    v: true
    sudo: true
  lint:
    name: flake8
