---
# role: ansible-role-ssh
# file: molecule/kvm/molecule.yml

dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/shared/yamllint.yml
platforms:
  - name: ssh-alpine37
    image: "alpine:3.7"
  - name: ssh-alpine38
    image: "alpine:3.8"
  - name: ssh-alpine39
    image: "alpine:3.9"
  - name: ssh-amazon2
    image: "jam82/amazon-molecule:2"
  - name: ssh-arch
    image: "jam82/arch-molecule"
  - name: ssh-centos6
    image: "jam82/centos-molecule:6"
  - name: ssh-centos7
    image: "jam82/centos-molecule:7"
  - name: ssh-debian8
    image: "debian:jessie"
  - name: ssh-debian9
    image: "debian:stretch"
  - name: ssh-opensuse-leap
    image: "opensuse:leap"
  - name: ssh-oracle7
    image: "oraclelinux:7"
  - name: ssh-ubuntu1604
    image: "ubuntu:16.04"
  - name: ssh-ubuntu1804
    image: "ubuntu:18.04"
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
  playbooks:
    converge: ../shared/playbook.yml
  inventory:
    group_vars:
      all:
        role_ssh_enabled: true
        sshd_listen_addr_v4: ['0.0.0.0']
scenario:
  name: default
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore"
  directory: ../tests
  options:
    v: true
    sudo: true
  lint:
    name: flake8
