---
# role: ansible-role-ssh
# file: molecule/kvm/molecule.yml

dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/shared/yamllint.yml
platforms:
  - name: ssh-arch
    image: "arch-molecule:latest"
    pre_build_image: true
  #   pre_build_image: true
  #   privileged: true
  #   volume_mounts:
  #     - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  # - name: ssh-centos6
  #   image: "jam82/centos-molecule:6"
  #   pre_build_image: true
  #   privileged: true
  #   volume_mounts:
  #     - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ssh-centos7
    image: "centos-molecule:7"
    pre_build_image: true
  - name: ssh-debian8
    image: "debian-molecule:8"
    pre_build_image: true
  - name: ssh-debian9
    image: "debian-molecule:9"
    pre_build_image: true
  - name: ssh-debian10
    image: "debian-molecule:10"
    pre_build_image: true
  # - name: ssh-opensuse-leap
  #   image: "opensuse:leap"
  #   privileged: true
  #   volume_mounts:
  #     - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  # - name: ssh-oracle7
  #   image: "oraclelinux:7"
  #   privileged: true
  #   volume_mounts:
  #     - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ssh-ubuntu1604
    image: "ubuntu-molecule:16.04"
    pre_build_image: true
  - name: ssh-ubuntu1804
    image: "ubuntu-molecule:18.04"
    pre_build_image: true
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
  playbooks:
    converge: ../shared/playbook.yml
  inventory:
    group_vars:
      all:
        role_ssh_enabled: true
        sshd_listen_addr_v4: ['0.0.0.0']
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore"
  directory: ../tests
  options:
    v: true
    sudo: true
  lint:
    name: flake8
