---
# role: ansible-role-ssh
# file: molecule/kvm/molecule.yml

dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/shared/yamllint.yml
platforms:
  - name: ssh-alpine39
    image: "alpine:3.9"
  - name: ssh-amazon2
    image: "amazonlinux:2"
  - name: ssh-arch
    image: "archlinux/base"
  - name: ssh-centos7
    image: "centos:centos7"
  - name: ssh-debian9
    image: "debian:stretch"
  - name: ssh-opensuse-leap
    image: "opensuse:leap"
  - name: ssh-oracle7
    image: "oraclelinux:7"
  - name: ssh-ubuntu1804
    image: "ubuntu:18.04"
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
  playbooks:
    converge: ../shared/playbook.yml
  inventory:
    group_vars:
      all:
        role_ssh_enabled: true
scenario:
  name: default
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore"
  directory: ../tests
  options:
    v: true
    sudo: true
  lint:
    name: flake8
