---
# role: ansible-role-vscode
# file: molecule/default/prepare.yml

- name: Prepare
  hosts: all
  gather_facts: True
  become: True
  tasks:
    - name: Update pacman cache
      pacman:
        update_cache: yes
      when: ansible_distribution == 'Archlinux'
