---
# role: ansible-role-vscode
# file: molecule/podman/prepare.yml
- name: Prepare
  hosts: all
  gather_facts: True
  become: True
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_pkg_mgr == 'apt'

    - name: Update dnf cache
      dnf:
        update_cache: yes
      when: ansible_pkg_mgr == 'dnf'

    - name: Update pacman cache
      pacman:
        update_cache: yes
      when: ansible_pkg_mgr == 'pacman'

    - name: Update yum cache
      yum:
        update_cache: yes
      when: ansible_pkg_mgr == 'yum'

    - name: Update zypper cache
      zypper:
        update_cache: yes
      when: ansible_pkg_mgr == 'zypper'
